version: '3.3'
services:
  calculator:
    image:
      maratfayzelgayanov/ld_calculator:1.0
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./dist:/dist
    depends_on:
      - database
    links:
      - database
  database:
    image:
      postgres:12
    restart:
      always
    expose:
      - "5432"
    volumes:
      - /dbData:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'ZZZXXX5!#~a'
      POSTGRES_DB: 'leasingdepositsdb'