version: '3.8'
services:
  gui:
    image: maratfayzelgayanov/ld_front:1.0
    restart: always
    ports:
      - "8000:80"
    networks:
      - guiNetwork
  calculator:
    image: maratfayzelgayanov/ld_calculator:1.0
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./config:/config
    networks:
      - databaseNetwork
      - guiNetwork
    depends_on:
      - database
  database:
    image:
      postgres:12
    restart:
      always
    networks:
      - databaseNetwork
    expose:
      - "5432"
    volumes:
      - /dbData:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'ZZZXXX5!#~a'
      POSTGRES_DB: 'leasingdepositsdb'
networks:
  databaseNetwork:
  guiNetwork: