package LD.config.Security.model.Authority;

public enum ALL_AUTHORITIES
{
	USER_ADDER,
	USER_EDITOR,
	USER_DELETER,
	USER_READER,

	ROLE_ADDER,
	ROLE_EDITOR,
	ROLE_DELETER,
	ROLE_READER,

	COMPANY_ADDER,
	COMPANY_EDITOR,
	COMPANY_DELETER,
	COMPANY_READER,

	COUNTERPARTNER_ADDER,
	COUNTERPARTNER_EDITOR,
	COUNTERPARTNER_DELETER,
	COUNTERPARTNER_READER,

	CURRENCY_ADDER,
	CURRENCY_EDITOR,
	CURRENCY_DELETER,
	CURRENCY_READER,

	DEPOSIT_RATES_ADDER,
	DEPOSIT_RATES_EDITOR,
	DEPOSIT_RATES_DELETER,
	DEPOSIT_RATES_READER,

	DURATION_ADDER,
	DURATION_EDITOR,
	DURATION_DELETER,
	DURATION_READER,

	END_DATE_ADDER,
	END_DATE_EDITOR,
	END_DATE_DELETER,
	END_DATE_READER,

	ENTRY_ADDER,
	ENTRY_EDITOR,
	ENTRY_DELETER,
	ENTRY_READER,

	ENTRY_IFRS_ADDER,
	ENTRY_IFRS_EDITOR,
	ENTRY_IFRS_DELETER,
	ENTRY_IFRS_READER,

	EXCHANGE_RATE_ADDER,
	EXCHANGE_RATE_EDITOR,
	EXCHANGE_RATE_DELETER,
	EXCHANGE_RATE_READER,

	IFRS_ACC_ADDER,
	IFRS_ACC_EDITOR,
	IFRS_ACC_DELETER,
	IFRS_ACC_READER,

	LEASING_DEPOSIT_ADDER,
	LEASING_DEPOSIT_EDITOR,
	LEASING_DEPOSIT_DELETER,
	LEASING_DEPOSIT_READER,

	PERIOD_ADDER,
	PERIOD_EDITOR,
	PERIOD_DELETER,
	PERIOD_READER,

	PERIODS_CLOSED_ADDER,
	PERIODS_CLOSED_EDITOR,
	PERIODS_CLOSED_DELETER,
	PERIODS_CLOSED_READER,

	SCENARIO_ADDER,
	SCENARIO_EDITOR,
	SCENARIO_DELETER,
	SCENARIO_READER,

	LOAD_EXCHANGE_RATE_FROM_CBR,
	AUTO_ADDING_PERIODS,
	AUTO_CLOSING_PERIODS,
	CALCULATE;

	@Override
	public String toString()
	{
		return super.toString();
	}
}
